// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.DbData;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.AsqModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Global_GoWeightAfter")
                        .HasColumnType("int");

                    b.Property<float>("Global_MixingTime")
                        .HasColumnType("real");

                    b.Property<float>("Global_RefValue")
                        .HasColumnType("real");

                    b.Property<float>("Global_WeightTolMinus")
                        .HasColumnType("real");

                    b.Property<float>("Global_WeightTolPlus")
                        .HasColumnType("real");

                    b.Property<int>("ROB1_Downtime_Time")
                        .HasColumnType("int");

                    b.Property<int>("ROB1_FormNumber")
                        .HasColumnType("int");

                    b.Property<float>("ROB1_SetTemperature")
                        .HasColumnType("real");

                    b.Property<float>("ROB1_Temperature")
                        .HasColumnType("real");

                    b.Property<float>("ROB1_TimeDrying")
                        .HasColumnType("real");

                    b.Property<float>("ROB1_WeightActualValue")
                        .HasColumnType("real");

                    b.Property<int>("ROB2_Downtime_Time")
                        .HasColumnType("int");

                    b.Property<int>("ROB2_FormNumber")
                        .HasColumnType("int");

                    b.Property<float>("ROB2_SetTemperature")
                        .HasColumnType("real");

                    b.Property<float>("ROB2_Temperature")
                        .HasColumnType("real");

                    b.Property<float>("ROB2_TimeDrying")
                        .HasColumnType("real");

                    b.Property<float>("ROB2_WeightActualValue")
                        .HasColumnType("real");

                    b.Property<string>("connection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AsqDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
